In [1]:
import os 
import json
import pandas as pd
import numpy as np

In [2]:
notebook_path = os.getcwd()
notebook_path

'C:\\Users\\VEDANG BARMAN\\Desktop\\Regulatory Compliance Agent\\sandbox\\jupyter'

In [8]:
in_dir_data = os.path.abspath(os.path.join(notebook_path,"..","..","Data","notification_historical","updated_notifications.jsonl"))

In [9]:
data = pd.read_json(in_dir_data,lines = True)

In [10]:
data.head()

,id,title,category,url,text
0,12931,Reserve Bank of India (Non-Banking Financial C...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DOR/2025-26/373\nDOR.FIN.REC.No.292/03-10-...
1,12932,Reserve Bank of India (Non-Operative Financial...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DoR/2025-26/372\nDoR.LIC.REC.No.291/16.13....
2,12933,Reserve Bank of India (Non-Banking Financial C...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DOR/2025-26/371\nDOR.FIN.REC.290/ 03-10-03...
3,12934,Reserve Bank of India (Non-Banking Financial C...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DOR/2025-26/370\nDOR.FIN.REC.No.289/03.10....
4,12935,Reserve Bank of India (Mortgage Guarantee Comp...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DOR/2025-26/369\nDOR.FIN.REC.No.288/23-11-...

In [11]:
data.isnull().sum()

id          0
title       0
category    0
url         0
text        0
dtype: int64

In [12]:
data["doc_type"] = 'circular'
data.head()

,id,title,category,url,text,doc_type
0,12931,Reserve Bank of India (Non-Banking Financial C...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DOR/2025-26/373\nDOR.FIN.REC.No.292/03-10-...,circular
1,12932,Reserve Bank of India (Non-Operative Financial...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DoR/2025-26/372\nDoR.LIC.REC.No.291/16.13....,circular
2,12933,Reserve Bank of India (Non-Banking Financial C...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DOR/2025-26/371\nDOR.FIN.REC.290/ 03-10-03...,circular
3,12934,Reserve Bank of India (Non-Banking Financial C...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DOR/2025-26/370\nDOR.FIN.REC.No.289/03.10....,circular
4,12935,Reserve Bank of India (Mortgage Guarantee Comp...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DOR/2025-26/369\nDOR.FIN.REC.No.288/23-11-...,circular

In [13]:
in_dir_master_directory = os.path.abspath(os.path.join(notebook_path,"..","..","Data","master_directory","master_directory.jsonl"))

In [14]:
data_directory = pd.read_json(in_dir_master_directory,lines= True)

In [15]:
data_directory.head()

,id,title,category,url,text
0,12931,Reserve Bank of India (Non-Banking Financial C...,NBFC,https://rbi.org.in/scripts/BS_ViewMasDirection...,RBI/DOR/2025-26/373\nDOR.FIN.REC.No.292/03-10-...
1,12932,Reserve Bank of India (Non-Operative Financial...,NBFC,https://rbi.org.in/scripts/BS_ViewMasDirection...,RBI/DoR/2025-26/372\nDoR.LIC.REC.No.291/16.13....
2,12933,Reserve Bank of India (Non-Banking Financial C...,NBFC,https://rbi.org.in/scripts/BS_ViewMasDirection...,RBI/DOR/2025-26/371\nDOR.FIN.REC.290/ 03-10-03...
3,12934,Reserve Bank of India (Non-Banking Financial C...,NBFC,https://rbi.org.in/scripts/BS_ViewMasDirection...,RBI/DOR/2025-26/370\nDOR.FIN.REC.No.289/03.10....
4,12935,Reserve Bank of India (Mortgage Guarantee Comp...,NBFC,https://rbi.org.in/scripts/BS_ViewMasDirection...,RBI/DOR/2025-26/369\nDOR.FIN.REC.No.288/23-11-...

In [17]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(data_directory['title'])

0     Reserve Bank of India (Non-Banking Financial C...
1     Reserve Bank of India (Non-Operative Financial...
2     Reserve Bank of India (Non-Banking Financial C...
3     Reserve Bank of India (Non-Banking Financial C...
4     Reserve Bank of India (Mortgage Guarantee Comp...
5     Reserve Bank of India (Non-Banking Financial C...
6     Reserve Bank of India (Core Investment Compani...
7     Reserve Bank of India (Standalone Primary Deal...
8     Reserve Bank of India (Housing Finance Compani...
9     Reserve Bank of India (Non-Banking Financial C...
10    Reserve Bank of India (Non-Banking Financial C...
11    Reserve Bank of India (Non-Banking Financial C...
12    Reserve Bank of India (Non-Banking Financial C...
13    Reserve Bank of India (Non-Banking Financial C...
14    Reserve Bank of India (Non-Banking Financial C...
15    Reserve Bank of India (Non-Banking Financial C...
16    Reserve Bank of India (Non-Banking Financial C...
17    Reserve Bank of India (Non-Banking Financial C...
18    Reserve Bank of India (Non-Banking Financial C...
19    Reserve Bank of India (Non-Banking Financial C...
20    Reserve Bank of India (Non-Banking Financial C...
21    Reserve Bank of India (Non-Banking Financial C...
22    Reserve Bank of India (Non-Banking Financial C...
23    Reserve Bank of India (Non-Banking Financial C...
24    Reserve Bank of India (Non-Banking Financial C...
25    Reserve Bank of India (Non-Banking Financial C...
26    Reserve Bank of India (Non-Banking Financial C...
27    Reserve Bank of India (Non-Banking Financial C...
28    Reserve Bank of India (Non-Banking Financial C...
29    Reserve Bank of India (Non-Banking Financial C...
30    Reserve Bank of India (Non-Banking Financial C...
31    Reserve Bank of India (Non-Banking Financial C...
32    Reserve Bank of India (Non-Banking Financial C...
33    Reserve Bank of India (Non-Banking Financial C...
34    Reserve Bank of India (Non-Banking Financial C...
35    Reserve Bank of India (Payments Banks - Superv...
36    Reserve Bank of India (Payments Banks – Statut...
37    Reserve Bank of India (Payments Banks - Intern...
38    Reserve Bank of India (Payments Banks – Fraud ...
39    Reserve Bank of India (Payments Banks – Digita...
40    Reserve Bank of India (Payments Banks - Cybers...
41    Reserve Bank of India (Payments Banks – Concur...
Name: title, dtype: str