In [1]:
import re
import pandas as pd
import os 

notebook_path= os.getcwd()
in_dir_notifications  = os.path.abspath(os.path.join(notebook_path,"..","..","Data","notification_historical","updated_notifications.jsonl"))
in_dir_master_direction = os.path.abspath(os.path.join(notebook_path,"..","..","Data","master_directory","master_directory.jsonl"))
circulars = pd.read_json(in_dir_notifications, lines=True)
master_directions = pd.read_json(in_dir_master_direction, lines = True)
# regexes to catch "Reserve Bank of India (X) ... Directions" and the no-paren variant
p1 = re.compile(r"Reserve Bank of India\s*[-–—]?\s*\(([^)]+)\)\s*(?:[A-Za-z]+\s+){0,3}Directions", re.IGNORECASE)
p2 = re.compile(r"Reserve Bank of India\s*[-–—]\s*([A-Za-z ,]+?),?\s*Directions", re.IGNORECASE)

norm = lambda s: re.sub(r"\s+", " ", s.replace("–","-").replace("—","-")).strip(" ,-").lower()

# extract candidate names from title + text
circulars["found_title"] = circulars["title"].apply(lambda t: [norm(x) for x in (p1.findall(t) + p2.findall(t))] if isinstance(t, str) else [])
circulars["found_text"]  = circulars["text"].apply(lambda t: [norm(x) for x in (p1.findall(t) + p2.findall(t))] if isinstance(t, str) else [])

# build master lookup: normalized name -> master direction id
master_lookup = {}
for _, r in master_directions.iterrows():
    for name in [norm(x) for x in (p1.findall(r["title"]) + p2.findall(r["title"]))]:
        master_lookup[name] = r["id"]

# match: prefer title hit, fall back to text hit
def _match(row):
    for n in row["found_title"]:
        if n in master_lookup: return master_lookup[n], "title_match"
    for n in row["found_text"]:
        if n in master_lookup: return master_lookup[n], "text_match"
    return None, "no_match",

circulars[["matched_id", "match_method"]] = circulars.apply(lambda r: pd.Series(_match(r)), axis=1)

# stats
print(circulars["match_method"].value_counts())
print(f"matched: {(circulars['match_method']!='no_match').mean():.1%}")

circulars[["id","title","found_title","matched_id","match_method"]]

match_method
no_match       97
title_match    34
text_match      7
Name: count, dtype: int64
matched: 29.7%

,id,title,found_title,matched_id,match_method
0,13167,Reserve Bank of India (Setting Up of Wholly Ow...,[],NaN,no_match
1,13168,Reserve Bank of India (Universal Banks – Licen...,[],NaN,no_match
2,13169,Compliance with Know Your Customer (KYC) norms,[],12943.0,text_match
3,13170,Consolidation of Regulations – Withdrawal of c...,[],NaN,no_match
4,13171,Compliance with Know Your Customer (KYC) norms,[],NaN,no_match
...,...,...,...,...,...
133,13675,Formation of new districts in the Union Territ...,[],NaN,no_match
134,13676,"Implementation of Section 51A of UAPA, 1967: U...",[],NaN,no_match
135,13677,"Implementation of Section 51A of UAPA, 1967: U...",[],NaN,no_match
136,13678,"Implementation of Section 51A of UAPA, 1967: U...",[],NaN,no_match
137,13679,Reserve Bank of India (Non-Banking Financial C...,[non-banking financial companies - concentrati...,12953.0,title_match

In [2]:
no_match = circulars[circulars["match_method"] == "no_match"]
print(len(no_match))
for t in no_match["title"].head(10):
    print("-", t)
no_match["text"].iloc[0]

97
- Reserve Bank of India (Setting Up of Wholly Owned Subsidiaries by Foreign Banks) Guidelines, 2025 (Updated as on April 1, 2026)
- Reserve Bank of India (Universal Banks – Licensing) Guidelines, 2025
- Consolidation of Regulations – Withdrawal of circulars
- Compliance with Know Your Customer (KYC) norms
- Liberalised Remittance Scheme (LRS)- Submission of ‘LRS Daily Return’ by Authorised Dealers- Category -II banks/ entities and Full- Fledged Money Changers
- Liquidity Adjustment Facility - Change in rates
- Standing Liquidity Facility for Primary Dealers
- Penal Interest on shortfall in CRR and SLR requirements - Change in Bank Rate
- Reserve Bank of India (Non-Operative Financial Holding Company) (Amendment) Directions, 2025
- Export and Import of Indian Currency to or from Nepal and Bhutan

'RBI/DOR/2025-26/144\nNovember 28, 2025\nPrevious Versions\nReserve Bank of India (Setting Up of Wholly Owned Subsidiaries by Foreign Banks) Guidelines, 2025 (Updated as on April 1, 2026)\nA. Background\nThe global financial crisis of 2008 demonstrated that the growing complexity and interconnectedness of financial institutions, coupled with the lack of effective cross-border resolution regimes, severely constrained the ability of home and host authorities to cope with the failure of too big to fail (TBTF) and too connected to fail (TCTF) institutions. Globally, several policy options have been proposed to address these challenges, including measures to contain the negative externalities arising out of size and interconnectedness, strengthening the capital and liquidity buffers, and enhancing the resolvability of such institutions. The lessons from the global financial crisis support the case for domestic incorporation of foreign banks. The main advantages of local incorporation include:\nCreation of separate legal entities with their own capital base and local board of directors;\nClear delineation between the assets and liabilities of the domestic bank and those of its foreign parent, with ring fenced capital and assets within the host country;\nClarity and certainty regarding the applicability of the laws of country of incorporation on the locally incorporated subsidiary;\nA locally incorporated bank has its own board of directors which are required to act in the best interests of the bank and safeguard the interests of depositors and creditors;\nLocal incorporation provides effective control to the local regulators.\nAccordingly, several jurisdictions require foreign banks to adopt local incorporation mainly for (i) protecting local retail depositors, (ii) easing the resolution process, and (iii) affording greater regulatory comfort.\nIn India, the Reserve Bank of India (RBI) allowed foreign banks, if eligible, to establish presence through a single mode i.e. either the branch mode or the wholly owned subsidiary (WOS) mode.\nExplanation: As per the road map for presence of foreign banks in India, announced in 2005, new entrants could choose either the branch mode or a 100% wholly owned subsidiary (WOS), subject to the single -mode presence criterion. However, no foreign bank opted for 100 per cent owned subsidiary route.\nBuilding on lessons learnt from the crisis, the RBI issued a Discussion Paper in January 2011 on the mode of presence of foreign banks in India. Based on the feedback received, the Scheme for setting up WOS by foreign banks in India has been finalised. It has been decided, as hitherto, to allow foreign banks to operate in India either through branch mode or through a wholly owned subsidiary (WOS) with near national treatment. The foreign banks have to choose one of the above two modes of presence and shall be governed by the principle of single mode of presence.\nAccordingly, on\nNovember 06, 2013\n, the Reserve Bank, in exercise of its power under Section 35A read with Section 44A of the Banking Regulation Act, 1949, and in the public interest as well as in the interest of banking policy, issued a ‘Scheme for Setting up of Wholly Owned Subsidiaries (WOS) by foreign banks in India.\nB. The Scheme\n1. Branch mode or wholly owned subsidiary\n(1) All foreign banks which are not carrying on banking business in India and which wish to do so in the future and to whom the matters referred to in paragraph 3 apply shall carry on banking business in India only through a wholly owned subsidiary.\n(2) Foreign banks which are not carrying on banking business in India and which wish to do so in the future and to whom the matters referred to in paragraph 3 do not apply have the option to carry on banking business in India either through a wholly owned subsidiary or through the branch mode. If they choose to carry on banking business through the branch mode, and in case at a later date they come within the purview of paragraph 3, they shall convert their branches into WOS.\n(3) Foreign banks which commenced banking business in India from August 2010 onwards were required to furnish an undertaking that they would convert their branches into wholly owned subsidiaries if so, required by RBI. Accordingly, such banks shall convert their branches into a wholly owned subsidiary if the matters specified in paragraph 3 apply to them.\n(4) Foreign banks which commenced banking business in India before August 2010 shall have the option either to continue their banking business through the branch mode or to convert those branches into a wholly owned subsidiary.\n(5) The branch expansion of both the existing foreign banks and the new entrants present in the branch mode would be subject to India’s WTO commitments.\n(6) In respect of foreign banks which are presently carrying on banking business in India, and which are required to convert their branches into a wholly owned subsidiary or opt to do so, the conversion shall only be in accordance with a scheme mandated in the public interest to be approved by RBI under Section 44A of the Banking Regulation Act 1949 and which is in accordance with the conditions specified in paragraph 19.\n2. Eligibility for setting up a wholly owned subsidiary\n(1) Setting up of WOS by a foreign bank in India should have the approval of the home country regulator/supervisor.\n(2) A foreign bank applying for setting up a WOS in India must satisfy RBI that it is subject to adequate prudential supervision as per internationally accepted standards, which includes consolidated supervision in its home country.\n(3) The factors taken into account, while considering applications for setting up WOS in India would include the following:\nEconomic and political relations with the country of incorporation of the parent bank,\nReciprocity with home country of the parent bank,\nFinancial soundness,\nOwnership pattern,\nInternational and home country ranking of the parent bank by a reputed agency,\nHome country/parent bank rating by a rating agency of international repute such as Moody Investors Service, Standard & Poor’s and Fitch Ratings,\nInternational presence of the bank,\nAdequate risk management and internal control systems.\nThese criteria represent the minimum that an applicant will need to meet for applying to RBI for granting a licence under Section 22 of the Banking Regulation Act, 1949 (to set up a bank as a WOS of the parent bank) and is not an exhaustive list. The final decision to grant licence will be that of RBI.\n3. Conditions requiring presence as WOS only\n(1) Foreign banks which have commenced banking business in India after August 2010 or foreign banks which are not at present carrying on banking business in India but wish to do so in the future shall carry on banking business in India only through a wholly owned subsidiary, if any of the matters as described hereunder are applicable:\nBanks incorporated in a jurisdiction having legislation giving a preferential claim to deposits of home country in a winding up proceedings;\nBanks that do not have adequate disclosure requirements in their home jurisdiction;\nBanks with complex structures;\nBanks which are not widely held;\nReserve Bank of India is not satisfied with the adequacy of supervisory arrangements (including disclosure arrangements) and market discipline in the country of their incorporation; and\nFor any other reason that the Reserve Bank of India considers necessary for subsidiary form of presence of the bank; or\n(2) If a foreign bank, which has set up its presence in India through branch mode after August 2010, is considered by RBI as being systemically important by virtue of the size of its business.\nExplanation: A foreign bank operating under branch mode of presence in India would be considered to be systematically important once its assets in Indian books (on balance sheet and credit equivalent of off-balance sheet items) become 0.25 per cent of the total assets (inclusive of credit equivalent of off-balance sheet items) of all scheduled commercial banks in India as on March 31 of the preceding year. RBI would furnish consolidated data on credit equivalent of off-balance sheet items for the banking industry for this purpose.\n4. National treatment\n(1) WOSs of the foreign banks, will be treated as “foreign banks” in line with Foreign Exchange Management (Non-Debt Instruments) Rules, 2019 (NDI Rules) read with\nMaster Direction – Foreign Investment in India\n.\n(2) Providing the extent of national treatment to WOS of foreign banks needs to be considered from the financial stability perspective. From financial stability perspective downside risk may arise if the foreign banks, i.e., WOSs of the foreign banks and foreign bank branches together come to dominate the domestic financial system. To address this risk, restrictions would be placed on further entry of new WOSs of foreign banks, when the capital and reserves of the foreign banks (i.e., WOSs and foreign bank branches) in India exceed 20% of the capital and reserves of the banking system. In such eventuality prior approval of RBI will be required for capital infusion into the existing WOSs of foreign banks. As regards foreign banks in branch mode of presence, as per the WTO commitments licences for new foreign banks may be denied when the maximum share of assets in India both on and off-balance sheet of foreign banks’ branches to total assets both on and off- balance sheet of the banking system exceeds 15 per cent.\n5. Minimum capital requirement\n(1) The initial minimum paid-up voting equity capital for a WOS shall be ₹500 crore.\n(2) The newly set up WOS of the foreign bank would be required to bring in the entire amount of initial capital upfront, which should be funded by free foreign exchange remittance from its parent.\n(3) In the case of an existing foreign bank having branch presence in India, which desires or is required to convert into a WOS:\n(i) It should convert its branch capital into the capital of WOS. The components, elements and eligibility criteria of the regulatory capital instruments for the WOS would be as applicable to the other domestic banks as stipulated in the\nReserve Bank of India (Commercial Banks – Prudential Norms on Capital Adequacy) Directions, 2025\n.\nExplanation: The elements and eligibility criteria of regulatory capital instruments for existing foreign bank branches are different from those applicable to domestic banks. Accordingly, conversion of branches of an existing foreign bank into WOS would require re-organisation of the capital structure. The WOS would be allowed to repatriate the ineligible regulatory capital to its parent with prior approval of RBI.\n(ii) It shall have a minimum net worth of ₹500 crore.\nExplanation: Net worth would comprise Paid-up capital plus Free Reserves including Share Premium but excluding Revaluation Reserves, plus Investment Fluctuation Reserve and credit balance in Profit & Loss account, less debit balance in Profit and Loss account, Accumulated Losses, and Intangible Assets. No general or specific provisions should be included in computation of net worth.\n(iii) If the net worth upon conversion is less than the minimum capital prescribed under these guidelines, the shortfall shall have to be brought in, towards infusion of equity, upfront from its parent as inward remittance.\n(iv) The WOS shall meet the Basel III requirements on a continuous basis from the time of its entry / conversion. WOS shall, however, maintain a minimum capital adequacy ratio, on a continuous basis for an initial period of three years from the commencement of its operations, at 10 per cent i.e. one per cent higher than that required under Basel III standards.\nIn addition, WOS shall also maintain capital conservation buffer and other buffers as applicable under extant capital adequacy framework.\n6. Use of group resources\n(1) The WOS shall be responsible for the core management functions which cannot be outsourced including to Group entities whether in India or abroad as laid down in\nReserve Bank of India (Commercial Banks – Managing Risks in Outsourcing) Directions, 2025\n. The said Direction also govern IT services including its outsourcing which will also be applicable to WOSs of foreign banks.\n7.\nCorporate governance:\nThe composition of the board of directors of WOS should meet the following requirements:\n(1) not less than 51 percent of the total number of members of the board of directors shall consist of persons as defined under Section 10A of the Banking Regulation Act, 1949;\n(2) not less than two-third of the directors should be non-executive directors;\n(3) not less than one-third of the directors should be independent of the management of the subsidiary in India, its parent and any subsidiary or other associate of the foreign bank parent;\n(4) not less than 50 per cent directors should be Indian nationals/NRIs/PIOs subject to the condition that one-third of the directors are Indian nationals resident in India;\n(5) WOSs of foreign banks will have Part-time Chairman and full time Chief Executive Officer (CEO);\n(6) RBI’s approval for appointment/re-appointment of the Part-time Chairman (non-executive director) should be obtained in terms of Section 10B(1A) of the Banking Regulation Act, 1949;\n(7) RBI’s approval for appointment/re-appointment of the CEO/ Whole Time Directors including remuneration and other terms of appointment should be obtained in terms of Section 35B of the Banking Regulation Act, 1949;\n(8) The Guidelines on Compensation of Whole Time Directors /Chief Executive Officers, as applicable to private sector banks in India, under\nReserve Bank of India (Commercial Banks – Governance) Directions, 2025\n, shall also be applicable to WOSs;\n(9) The CEO will be appointed on full time basis and should be resident in India;\n(10) The directors should conform to the ‘Fit and Proper’ criteria as laid down in\nReserve Bank of India (Commercial Banks – Governance) Directions, 2025\n, as amended from time to time; and\n(11) All other provisions of the Banking Regulation Act, 1949 in respect of composition of board of directors, as applicable to private sector banks in India would also be applicable to WOSs.\n8. Statutory, regulatory, prudential and other requirements\n(1) The WOS shall be governed by the provisions of the Companies Act, 2013, Banking Regulation Act, 1949, Reserve Bank of India Act, 1934, Foreign Exchange Management Act, 1999, Payment and Settlement Systems Act, 2007 and other relevant statutes, directives, prudential regulations and other guidelines/instructions issued by RBI and other regulators from time to time.\n(2) In all the cases where foreign bank parent/group of the WOS in India has NBFCs, the regulatory framework for consolidated prudential reporting and supervision, currently applicable to branches of foreign banks as laid down in\nReserve Bank of India (Commercial Banks – Undertaking of Financial Services) Directions, 2025\nwill also be applicable to WOS.\n(3) In case Know Your Customer (KYC)/Anti Money Laundering (AML)/Combating the Financing of Terrorism (CFT) deficiencies are found in respect of any jurisdiction / bank, banks from such jurisdictions would be subjected to enhanced prudential requirements.\n9. Raising of Non-equity capital in India\n(1) WOS of foreign banks may raise rupee resources through issue of non-equity capital instruments, as allowed to domestic banks.\n10. Branch Expansion/Authorisation\n(1) The guidelines contained in\nReserve Bank of India (Commercial Banks – Branch Authorisation) Directions, 2025\n, as applicable to domestic scheduled commercial banks and as amended from time to time would generally be applicable to WOS of foreign banks.\n(2) WOS would require prior approval of RBI for opening branches at certain locations that are sensitive from the perspective of national. A list of such centres would be made available to WOSs by RBI.\n11. Priority sector lending requirements for WOS\n(1) The WOSs shall comply with the priority sector lending requirements, as applicable to Domestic Commercial Banks/ WoS of Foreign banks under\nMaster Directions - Reserve Bank of India (Priority Sector Lending – Targets and Classification) Directions, 2025\n.\n(2) An existing foreign bank with less than 20 branches, opting to convert into a WOS, will be allowed a maximum period of five years, based on the action plan submitted to RBI, to achieve priority sector sub-targets. This relaxation will be available from the date of conversion into a WOS.\n12. Use of credit rating and parent / head office support\n(1) The parent of the WOS would be required to issue a letter of comfort (LOC) to the Reserve Bank for meeting the liabilities of the WOS. Reserve Bank would take into account this commitment of the parent to support the subsidiary before a foreign bank is allowed to set up a WOS in India.\n(2) On arm’s length basis, WOSs would be permitted to use parental guarantees/credit rating only for the purpose of providing custodial services and for international operations. However, WOS should not provide counter guarantee to its parent for such support.\n13. Declaration of dividends\n(1) The WOS of a foreign bank, being a company incorporated in India, may declare dividend like domestic banks subject to criteria laid down in\n1\n[\nReserve Bank of India (Commercial Banks – Prudential Norms on Declaration of Dividends and Remittance of Profit) Directions, 2026\n] which may be repatriated as per the provisions of FEMA 1999.\n14.\nInvestment by the WOS in subsidiaries and other companies:\nThe investment in subsidiaries and other companies by WOS would be guided by the extant instructions contained in\nReserve Bank of India (Commercial Banks – Undertaking of Financial Services) Directions, 2025\n, which, inter alia, include the following:\n(1) RBI does not encourage setting up of subsidiaries or significant investment in associates for activities that can be undertaken within the bank. Accordingly, in the case of WOS, approval for setting up subsidiaries or significant investment in associates will also factor in whether there are NBFCs set up by the parent banking group under FDI rules for undertaking same or similar activity;\n(2) The WOS shall maintain arm’s length relationship with parent’s group entities;\nExplanation: Group entities for this purpose would be as under: -\n(a) enterprises that directly, or indirectly through one or more intermediaries, control, or are controlled by, or are under common control with, the reporting enterprise (this includes holding companies, subsidiaries and fellow subsidiaries);\n(b) associates and joint ventures of the reporting enterprise and the investing party or venturer in respect of which the reporting enterprise is an associate or a joint venture;\n(c) individuals owning, directly or indirectly, an interest in the voting power of the reporting enterprise that gives them control or significant influence over the enterprise, and relatives of any such individual;\n(d) associates / joint ventures of the holding company and/or its fellow subsidiaries;\n(e) entities sharing common brand name with entities in (a), (b), (c), (d) above;\n(f) key management personnel and relatives of such personnel;\n(g) enterprises over which any person described in (c) or (f) is able to exercise significant influence. This includes enterprises owned by directors or major shareholders of the reporting enterprise and enterprises that have a member of key management in common with the reporting enterprise; For this purpose, control, significant influence, associate, joint venture, key management personnel, subsidiary and holding company shall have the same meaning as defined in the Accounting Standard AS 18 (Related Party Disclosures) issued by the Institute of Chartered Accountants of India.\n(3) In taking a view on whether an entity belongs to

In [14]:
circulars["footnotes"] = circulars["text"].apply(
    lambda t: [
        {
            "action": action.strip(),
            "effective_date": eff_date.strip(),
            "vide_ref": norm(vide_ref),
            "notification_date": notif_date.strip(),
        }
        for action, eff_date, vide_ref, notif_date in footnote_pattern.findall(t)
    ] if isinstance(t, str) else []
)

master_directions["footnotes"] = master_directions["text"].apply(
    lambda t: [
        {
            "action": action.strip(),
            "effective_date": eff_date.strip(),
            "vide_ref": norm(vide_ref),
            "notification_date": notif_date.strip(),
        }
        for action, eff_date, vide_ref, notif_date in footnote_pattern.findall(t)
    ] if isinstance(t, str) else []
)

print(f"circulars with footnotes: {(circulars['footnotes'].apply(len) > 0).sum()} / {len(circulars)}")
print(f"master_directions with footnotes: {(master_directions['footnotes'].apply(len) > 0).sum()} / {len(master_directions)}")

circulars[["id","title","footnotes"]]

circulars with footnotes: 1 / 138
master_directions with footnotes: 25 / 44

,id,title,footnotes
0,13167,Reserve Bank of India (Setting Up of Wholly Ow...,"[{'action': 'Substituted', 'effective_date': '..."
1,13168,Reserve Bank of India (Universal Banks – Licen...,[]
2,13169,Compliance with Know Your Customer (KYC) norms,[]
3,13170,Consolidation of Regulations – Withdrawal of c...,[]
4,13171,Compliance with Know Your Customer (KYC) norms,[]
...,...,...,...
133,13675,Formation of new districts in the Union Territ...,[]
134,13676,"Implementation of Section 51A of UAPA, 1967: U...",[]
135,13677,"Implementation of Section 51A of UAPA, 1967: U...",[]
136,13678,"Implementation of Section 51A of UAPA, 1967: U...",[]
137,13679,Reserve Bank of India (Non-Banking Financial C...,[]

In [8]:
import re
import pandas as pd
import os

notebook_path = os.getcwd()
in_dir_notifications_raw = os.path.abspath(os.path.join(notebook_path,"..","..","Data","notification_historical","notification.jsonl"))
in_dir_master_direction = os.path.abspath(os.path.join(notebook_path,"..","..","Data","master_directory","master_directory.jsonl"))

circulars = pd.read_json(in_dir_notifications_raw, lines=True)
master_directions = pd.read_json(in_dir_master_direction, lines=True)

# ── citation regexes ─────────────────────────────────────
DOC_TYPE = r"(?:Directions?|Guidelines?|Regulations?|Rules?|Circulars?|Framework|Scheme)"
p1 = re.compile(
    r"Reserve Bank of India\s*[-–—]?\s*\(([^)]+)\)"
    r"(?:\s*\([^)]*\))*"
    r"\s*(?:[A-Za-z]+\s+){0,3}" + DOC_TYPE,
    re.IGNORECASE
)
p2 = re.compile(r"Reserve Bank of India\s*[-–—]\s*([A-Za-z ,]+?),?\s*Directions", re.IGNORECASE)
norm = lambda s: re.sub(r"\s+", " ", s.replace("–","-").replace("—","-")).strip(" ,-").lower()

# ── extraction ────────────────────────────────────────────
circulars["found_title"] = circulars["title"].apply(lambda t: [norm(x) for x in (p1.findall(t)+p2.findall(t))] if isinstance(t, str) else [])
circulars["found_text"]  = circulars["text"].apply(lambda t: [norm(x) for x in (p1.findall(t)+p2.findall(t))] if isinstance(t, str) else [])

master_lookup = {}
for _, r in master_directions.iterrows():
    for name in [norm(x) for x in (p1.findall(r["title"])+p2.findall(r["title"]))]:
        master_lookup[name] = r["id"]

def _match(row):
    for n in row["found_title"]:
        if n in master_lookup: return master_lookup[n], "title_match"
    for n in row["found_text"]:
        if n in master_lookup: return master_lookup[n], "text_match"
    return None, "no_match"

circulars[["matched_id","match_method"]] = circulars.apply(lambda r: pd.Series(_match(r)), axis=1)

# ── three-bucket split ───────────────────────────────────
nbfc_pattern = r"non[\s-]?banking financial compan|nbfc"
circulars["is_nbfc_relevant"] = (
    circulars["text"].str.contains(nbfc_pattern, case=False, na=False) |
    circulars["title"].str.contains(nbfc_pattern, case=False, na=False)
)
circulars["has_citation"] = circulars["found_title"].apply(len).gt(0) | circulars["found_text"].apply(len).gt(0)

def bucket(row):
    if row["match_method"] != "no_match":
        return "linked"
    if not row["is_nbfc_relevant"]:
        return "not_nbfc"
    if not row["has_citation"]:
        return "nbfc_standalone"
    return "nbfc_citation_unmatched"

circulars["bucket"] = circulars.apply(bucket, axis=1)
print(circulars["bucket"].value_counts())

bucket
not_nbfc                   530
nbfc_citation_unmatched    134
linked                     102
Name: count, dtype: int64

In [9]:
for b in ["not_nbfc", "nbfc_standalone", "nbfc_citation_unmatched"]:
    print(f"\n=== {b} ===")
    print(circulars[circulars["bucket"]==b]["title"].head(10).to_string())

=== not_nbfc ===
41    Reserve Bank of India (All India Financial Ins...
43    Reserve Bank of India (All India Financial Ins...
48    Reserve Bank of India (All India Financial Ins...
49    Reserve Bank of India (All India Financial Ins...
57    Reserve Bank of India (All India Financial Ins...
60    Reserve Bank of India (Rural Co-operative Bank...
61    Reserve Bank of India (Rural Co-operative Bank...
62    Reserve Bank of India (Rural Co-operative Bank...
64    Reserve Bank of India (Rural Co-operative Bank...
65    Reserve Bank of India (Rural Co-operative Bank...

=== nbfc_standalone ===
Series([], )

=== nbfc_citation_unmatched ===
0     Reserve Bank of India (Credit Information Comp...
1     Reserve Bank of India (Credit Information Comp...
2     Reserve Bank of India (Asset Reconstruction Co...
4     Reserve Bank of India (Asset Reconstruction Co...
42    Reserve Bank of India (All India Financial Ins...
44    Reserve Bank of India (All India Financial Ins...
45    Reserve Bank of India (All India Financial Ins...
47    Reserve Bank of India (All India Financial Ins...
50    Reserve Bank of India (All India Financial Ins...
51    Reserve Bank of India (All India Financial Ins...

In [10]:
print(circulars["bucket"].value_counts(dropna=False))
print(len(circulars))

bucket
not_nbfc                   530
nbfc_citation_unmatched    134
linked                     102
Name: count, dtype: int64
766

In [11]:
circulars["found_text_lead"] = circulars["text"].apply(
    lambda t: [norm(x) for x in (p1.findall(t[:600]) + p2.findall(t[:600]))] if isinstance(t, str) else []
)
circulars["has_citation_lead"] = circulars["found_title"].apply(len).gt(0) | circulars["found_text_lead"].apply(len).gt(0)

def bucket_v2(row):
    if row["match_method"] != "no_match":
        return "linked"
    if not row["is_nbfc_relevant"]:
        return "not_nbfc"
    if not row["has_citation_lead"]:
        return "nbfc_standalone"
    return "nbfc_citation_unmatched"

circulars["bucket_v2"] = circulars.apply(bucket_v2, axis=1)
print(circulars["bucket_v2"].value_counts())

bucket_v2
not_nbfc                   530
nbfc_citation_unmatched    119
linked                     102
nbfc_standalone             15
Name: count, dtype: int64

In [13]:
pd.set_option('display.max_colwidth', 300)

# does anything here look like it SHOULDN'T be excluded?
print(circulars[circulars["bucket_v2"]=="not_nbfc"]["title"].sample(100, random_state=1).to_string())

106                                                                                                               Reserve Bank of India (Urban Co-operative Banks – Cash Reserve Ratio and Statutory Liquidity Ratio) Directions, 2025 (Updated as on August 25, 2026)
591                                                                                                                                       Reserve Bank of India (Commercial Banks – Cash Reserve Ratio and Statutory Liquidity Ratio) Third Amendment Directions, 2026
419                                                                                                                                                                                                                             NOP-INR position of Authorised Dealers
329                                                                                                                                                             Reserve Bank of India (Rural Co-operative Banks – Credit Risk Management) – Amendment Directions, 2026
99                                                                                                                                                                   Reserve Bank of India (Urban Co-operative Banks – Concentration Risk Management) Directions, 2025
128                                                                                                                                                   Reserve Bank of India (Regional Rural Banks – Credit Facilities) Directions, 2025 (Updated as on April 01, 2026)
456                                                                                                                                                   Reserve Bank of India (Rural Co-operative Banks– Undertaking of Financial Services) – Amendment Directions, 2026
567                                                                                                                                          Reserve Bank of India (All India Financial Institutions - Responsible Business Conduct) Second Amendment Directions, 2026
761                                                                                                                                                          Reserve Bank of India (Small Finance Banks – Interest Rate on Deposits)  Third Amendment Directions, 2026
396                                                                                                                                                              Reserve Bank of India (Payments Banks – Prudential Norms on Declaration of Dividend) Directions, 2026
435    Master Direction on Incentives for Currency Distribution and Exchange and Penalties / Penal Provisions for Bank Branches and Currency Chests for Deficiency in Rendering Customer Service and Reporting of Transactions / Balances (Updated as on May 27, 2026)
252                                                                                                                                                             Reserve Bank of India (Regional Rural Banks - Responsible Business Conduct) Amendment Directions, 2025
156                                                                                                                      Reserve Bank of India (Local Area Banks – Cash Reserve Ratio and Statutory Liquidity Ratio) Directions, 2025 (Updated as on January 22, 2026)
259                                                                                                                                                         Reserve Bank of India (Urban Co-operative Banks – Credit Information Reporting) Amendment Directions, 2025
640                                                                                                                                                          Reserve Bank of India (Commercial Banks – Resolution of Stressed Assets) Third Amendment Directions, 2026
549                                                                                                                              Reserve Bank of India (Rural Co-operative Banks – Cash Reserve Ratio and Statutory Liquidity Ratio) Second Amendment Directions, 2026
517                                                                                                                                    Reserve Bank of India [Disbursement of Government Pension by Agency Banks (ABs)] Directions, 2026 (Updated as on June 24, 2026)
307                                                                                                                                                                             Continuous Clearing and Settlement on Realisation in Cheque Truncation System: Phase 2
528                                                                                                                             Reserve Bank of India (Local Area Banks - Classification, Valuation, and Operation of Investment Portfolio) Amendment Directions, 2026
381                                                                                                                                                                            Foreign Exchange Management (Borrowing and Lending) (First Amendment) Regulations, 2026
209                                                                                                                                                  Reserve Bank of India (Small Finance Banks – Acquisition and Holding of Shares or Voting Rights) Directions, 2025
473                                                                                                                                                   Reserve Bank of India (Commercial Banks – Undertaking of Financial Services) – Second Amendment Directions, 2026
413                                                                                                                                    Reserve Bank of India (Local Area Banks – Financial Statements: Presentation and Disclosures) Second Amendment Directions, 2026
394                                                                                                                                 Reserve Bank of India (Commercial Banks – Prudential Norms on Declaration of Dividend and Remittances of Profits) Directions, 2026
341                                                                                                                                                      Reserve Bank of India (Small Finance Banks - Prudential Norms on Capital Adequacy) Amendment Directions, 2026
377                                                                                                                                               Reserve Bank of India (Small Finance Banks - Prudential Norms on Capital Adequacy) Second Amendment Directions, 2026
490                                                                                                                                    Reserve Bank of India (Local Area Banks – Income Recognition, Asset Classification and Provisioning) Amendment Directions, 2026
623                                                                                                                                                   Reserve Bank of India (Urban Co-operative Banks - Responsible Business Conduct) Third Amendment Directions, 2026
562                                                                                                                                                                   Reserve Bank of India (Payments Banks - Responsible Business Conduct) Amendment Directions, 2026
693                                                                                                                                                                            Reserve Bank of India (Urban Co-operative Banks - Compliance Function) Directions, 2026
641                                                                                                                                                      Reserve Bank of India (Small Finance Banks – Resolution of Stressed Assets) Second Amendment Directions, 2026
249                                                                                                                                                              Reserve Bank of India (Small Finance Banks - Responsible Business Conduct) Amendment Directions, 2025
164                                                                                                                                               Reserve Bank of India (Payments Banks – Responsible Business Conduct) Directions, 2025 (Updated as on April 1, 2026)
600                                                                                                                                                                 Reserve Bank of India [Rural Co-operative Banks - Kisan Credit Card (KCC) Scheme] Directions, 2026
611                                                                                                                                                 Reserve Bank of India (Rural Co-operative Banks - Prudential Norms on Capital Adequacy) Amendment Directions, 2026
114                                                                                                                                          Reserve Bank of India (Regional Rural Banks – Responsible Business Conduct) Directions, 2025 (Updated as on July 1, 2026)
649                                                                                                                          Reserve Bank of India (Small Finance Banks – Income Recognition, Asset Classification and Provisioning) Second Amendment Directions, 2026
683                                                                                                                                                                                       Reserve Bank of India (Local Area Banks – Concurrent Audit) Directions, 2026
571                                                                                                                                                  Reserve Bank of India (Small Finance Banks – Undertaking of Financial Services) Second Amendment Directions, 2026
565                                                                                                                                                  Reserve Bank of India (Urban Co-operative Banks - Responsible Business Conduct) Second Amendment Directions, 2026
241                                                                                                                                                     Reserve Bank of India (Commercial Banks – Acquisition and Holding of Shares or Voting Rights) Directions, 2025
339                                                                                                                         Reserve Bank of India (All India Financial Institutions – Financial Statements: Presentation and Disclosures) – Amendment Directions, 2026
725                                                                                                                                                                               Reserve Bank of India (Payments Banks – Governance) Third Amendment Directions, 2026
161                                                                                                                                                     Reserve Bank of India (Local Area Banks – Acquisition and Holding of Shares or Voting Rights) Directions, 2025
709                                                                                                                                 Reserve Bank of India (Small Finance Banks - Cybersecurity, Technology: Risk, Resilience and Assurance Framework) Directions, 2026
557                                                                                                                                                            Reserve Bank of India (All India Financial Institutions – Credit Facilities) Amendment Directions, 2026
293                                                                                                                                                                  Reserve Bank of India (Small Finance Banks – Credit Risk Management) – Amendment Directions, 2025
609                                                                                                                                               Reserve Bank of India (Regional Rural Banks - Prudential Norms on Capital Adequacy) Third Amendment Directions, 2026
57                                                                                                                                                                   Reserve Bank of India (All India Financial Institutions– Resource Raising Norms) Directions, 2025
424                                                                                                                         Reserve Bank of India (Commercial Banks – Financial Statements: Presentation and Disclosures) – Third Amendment Directions, 2026 (Revised)
316                                                                                                                                                                   Reserve Bank of India (Urban Co-operative Banks – Know Your Customer) Amendment Directions, 2025
635                                                                                                                                                                  Reserve Bank of India (Small Finance Banks – Credit Facilities) Fourth Amendment Directions, 2026
408                                                                                                                                   Reserve Bank of India (Commercial Banks – Financial Statements: Presentation and Disclosures) – Fifth Amendment Directions, 2026
423                                                                                                                                        Reserve Bank of India (Commercial Banks - Prudential Norms on Capital Adequacy) Second Amendment Directions, 2026 (Revised)
453                                                                                                                                           Reserve Bank of India (All India Financial Institutions – Undertaking of Financial Services) –Amendment Directions, 2026
344                                                                                                                                                                                                         Foreign Exchange Management (Guarantees) Regulations, 2026
673                                                                                                                                                                          Reserve Bank of India (Regional Rural Banks - Miscellaneous) Supervisory Directions, 2026
410                                                                                                                              Reserve Bank of India (Regional Rural Banks – Financial Statements: Presentation and Disclosures) – Second Amendment Directions, 2026
598                                                                                                                                                                      Reserve Bank of India [Small Finance Banks - Kisan Credit Card (KCC) Scheme] Directions, 2026
309                                                                                                                                                             Reserve Bank of India (Asset Reconstruction Companies – Know Your Customer) Amendment Directions, 2025
466                                                                                                                            Reserve Bank of India (Commercial Banks – Classification, Valuation, and Operation of Investment Portfolio)- Amendment Directions, 2026
727                                                                                                                                                Reserve Bank of India (Small Finance Banks – Prudential Norms on Capital Adequacy) Fifth Amendment Directions, 2026
698                                                                                                                                                                                    Reserve Bank of India (Payments Banks – Fraud Risk Management) Directions, 2026
750                                                                                                                                                               Formation of new districts in the Union Territory of Ladakh – Assignment of Lead Bank Responsibility
712                                                                                                                                                                              Reserve Bank of India (Commercial Banks – Miscellaneous) Supervisory Directions, 2026
469                                                                                                                                                  Reserve Bank of India (Urban Co-operative Banks – Undertaking of Financial Services) – Amendment Directions, 2026
404                                                                                                                                                Reserve Bank of India (Small Finance Banks - Prudential Norms on Capital Adequacy) Third Amendment Directions, 2026
655                                                                                                                             Reserve Bank of India (Local Area Banks – Income Recognition, Asset Classification and Provisioning) Second Amendment Directions, 2026
60                                                                                                                                                                                   Reserve Bank of India (Rural Co-operative Banks – Miscellaneous) Directions, 2025
691                                                                                                                            Reserve Bank of India (Urban Co-operative Banks – Cybersecurity, Technology: Risk, Resilience and Assurance Framework) Directions, 2026
560                                                                                                                                                          Reserve Bank of India (Commercial Banks - Responsible Business Conduct) Second Amendment Directions, 2026
540                                                                                                                                                                                 Submission of statement/return on Centralized Information Management System (CIMS)
79                                                                                                                               Reserve Bank of India (Rural Co-operative Banks – Prudential Norms on Capital Adequacy) Directions, 2025 (Updated as on May 15, 2026)
726                                                                                                                                      Reserve Bank of India (Payments Banks – Financial Statements: Presentation and Disclosures) Second Amendment Directions, 2026
433                                                                                                                           Reporting under Foreign Exchange Management Act, 1999 – Returns pertaining to Foreign Exchange Management (Guarantees) Regulations, 2026
162                                                                                                                                                             Reserve Bank of India (Payments Banks – Miscellaneous) Directions, 2025 (Updated as on April 01, 2026)

In [14]:
ref_pattern = re.compile(r"([A-Z]+(?:\.[A-Z]+)+\.\d+)/([\d-]+)/(\d{4}-\d{2})")

circulars["subject_code"] = circulars["text"].str.extract(ref_pattern)[1]
master_directions["subject_code"] = master_directions["text"].str.extract(ref_pattern)[1]

print(circulars["subject_code"].notna().mean())       # what % of circulars even have this line
print(master_directions["subject_code"].notna().mean())

0.49477806788511747
0.75

In [15]:
dupe_codes = master_directions.dropna(subset=["subject_code"]).groupby("subject_code")["id"].nunique()
dupe_codes[dupe_codes > 1]

subject_code
33-01-010    30
Name: id, dtype: int64

In [16]:
code_matches = circulars.merge(
    master_directions.dropna(subset=["subject_code"])[["id","subject_code"]],
    on="subject_code", how="left", suffixes=("", "_master")
)

# where code-match succeeds but your text/title match didn't
recovered = code_matches[(code_matches["match_method"] == "no_match") & code_matches["id_master"].notna()]
print(f"{len(recovered)} previously unmatched circulars recoverable via subject_code")

# where both methods matched, do they point to the same master direction?
both = code_matches[(code_matches["match_method"] != "no_match") & code_matches["id_master"].notna()]
disagreements = both[both["matched_id"] != both["id_master"]]
print(f"{len(disagreements)} / {len(both)} disagree between text-match and code-match")

4461 previously unmatched circulars recoverable via subject_code
1133 / 1177 disagree between text-match and code-match